export const departments = {
  1: { departmentId: 1, displayName: 'American Decorative Arts' },
  3: { departmentId: 3, displayName: 'Ancient Near Eastern Art' },
  4: { departmentId: 4, displayName: 'Arms and Armor' },
  5: {
    departmentId: 5,
    displayName: 'Arts of Africa, Oceania, and the Americas',
  },
  6: { departmentId: 6, displayName: 'Asian Art' },
  7: { departmentId: 7, displayName: 'The Cloisters' },
  8: { departmentId: 8, displayName: 'The Costume Institute' },
  9: { departmentId: 9, displayName: 'Drawings and Prints' },
  10: { departmentId: 10, displayName: 'Egyptian Art' },
  11: { departmentId: 11, displayName: 'European Paintings' },
  12: {
    departmentId: 12,
    displayName: 'European Sculpture and Decorative Arts',
  },
  13: { departmentId: 13, displayName: 'Greek and Roman Art' },
  14: { departmentId: 14, displayName: 'Islamic Art' },
  15: { departmentId: 15, displayName: 'The Robert Lehman Collection' },
  16: { departmentId: 16, displayName: 'The Libraries' },
  17: { departmentId: 17, displayName: 'Medieval Art' },
  18: { departmentId: 18, displayName: 'Musical Instruments' },
  19: { departmentId: 19, displayName: 'Photographs' },
  21: { departmentId: 21, displayName: 'Modern Art' },
};
